# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publishing_year', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('ISBN', models.CharField(blank=True, max_length=200)),
                ('online_stores', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
